version: '2'

services:
  nginx-proxy:
    image: nginx:1.26-alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # The vhost volume is only required if you
      # plan to obtain standalone certificates
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - ./deploy/http.conf:/etc/nginx/conf.d/http.conf

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./deploy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    labels:
      - 'com.github.nginx-proxy.docker-gen'

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=jerryc.nguyen91@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  chuannhadat_next:
    restart: always
    image: registry.gitlab.com/mkt-devops/web-deployments:chuannhadat_next
    container_name: chuannhadat_next
    ports:
      - '4500:4500'
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'
    environment:
      - VIRTUAL_HOST=nextjs.chuannhadat.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=4500
      - LETSENCRYPT_HOST=nextjs.chuannhadat.com
      - LETSENCRYPT_EMAIL=jerryc.nguyen91@gmail.com
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - ENABLE_BOT_PROTECTION=true
    command: 'node server.js'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4500/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - redis

volumes:
  vhost:
  conf:
  html:
  acme:
  certs:
  redis_data:
