// Constants for UI dimensions
export const SEARCH_BOX_WIDTH = 480;
export const SEARCH_BOX_PADDING = 16;
export const SEARCH_BOX_WIDTH_WITH_PADDING = SEARCH_BOX_WIDTH + SEARCH_BOX_PADDING * 2;
export const LISTING_PANEL_WIDTH = 400;
export const LISTING_PANEL_PADDING = 16;
export const LISTING_PANEL_WIDTH_WITH_PADDING = LISTING_PANEL_WIDTH + LISTING_PANEL_PADDING * 2;
