import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getUserAgentInfo } from "@utils/ssrUserAgent";

import "./globals.css";
import QueryProvider from "@utils/QueryProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isMobile } = getUserAgentInfo();
  const mobileClass = isMobile ? "isMobile" : "";

  return (
    <html lang="en">
      <body className={inter.className + ` ${mobileClass} `}>
        <QueryProvider>
          {children}
          <ToastContainer
            position="top-center"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
        </QueryProvider>
      </body>
    </html>
  );
}
